Vidly/Models/Customer.cs
//using Microsoft.Build.Framework;
using System.ComponentModel.DataAnnotations;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace Vidly.Models
{
    public class Customer
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        public bool IsSubscribedToNewsLetter { get; set; }
        public MembershipType MembershipType { get; set; }
        public byte MembershipTypeId { get; set; }

    }
}

Vidly/Models/ErrorViewModel.cs
namespace Vidly.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vidly/Models/MembershipType.cs
namespace Vidly.Models
{
    public class MembershipType
    {
        public byte Id { get; set; }
        public short SignUpFee { get; set; }
        public byte DurationInMonth { get; set; }
        public byte DiscountRate { get; set; }
    }
}

Vidly/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace Vidly.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
    }
}

Vidly/ViewModels/RandomMoveViewModel.cs
using Vidly.Models;

namespace Vidly.ViewModels
{
    public class RandomMoveViewModel
    {
        public Movie Movie{ get; set; }
        public List<Customer> Customers{ get; set; }

    }
}

Vidly/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.Entity;
using Vidly.Data;
using Vidly.Models;

namespace Vidly.Controllers
{
    public class CustomersController : Controller 
    {
        private VidlyContext _context;
        public List<Customer> Customers{ get; set; }
        public CustomersController(VidlyContext vidlyContext)
        {
            Customers = new List<Customer>()
            {
              new Customer(){Name="John Smith", Id=0},
              new Customer(){Name="Will Smith", Id=1}
            };
            _context = vidlyContext;
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public IActionResult New()
        {
            return View(); 
        }
        [Route("Customers/Index")]
        public IActionResult Index()
        {
            //var customers = new List<Customer>()
            //{ 
            //  new Customer(){Name="John Smith", Id=0},
            //  new Customer(){Name="Will Smith", Id=1}
            //};
            var customers = _context.Customers.Include(c=>c.MembershipType).ToList(); 
            // var customers1 = _context.Customers.Include<Customer>(c=>c.MembershipType) 

            return View(customers);
        }
        [Route("/Customers/Index/Details")]
        public IActionResult Details(int id) 
        {
            //var _Customers = Customers;
            //int number = 0;
            //var customer = new Customer();
            //foreach (var item in _Customers)
            //{
            //    if(item.Id==id)
            //    {
            //        number = 1;
            //        customer = item;
            //        return View(item);
            //    }
            //}
            //if(number==0)
            //return View();
            //else
            //{
            //    return View(customer);
            //}
            var customers = _context.Customers.SingleOrDefault(x => x.Id == id);  
            if(customers == null)
                return NotFound();
            else
                return View(customers);
        }
    }
}

Vidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Vidly.Data;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        private readonly VidlyContext _context;

        public MoviesController(VidlyContext context)
        {
            _context = context;
        } 
        public IActionResult Random()
        {
            var movie = new Movie() { Name = "Shrek" };
            var customers = new List<Customer>()
            { 
             new Customer{Name="Customer 1"},
             new Customer{Name="Customer 2"}
            };
            var ViewModel = new RandomMoveViewModel()
            {
                Movie = movie,
                Customers = customers
            };
            return View(ViewModel);
        }
        
    }
}

Vidly/Views/Customers/Details.cshtml
@model Vidly.Models.Customer

<h1>@Model.Name</h1>

Vidly/Views/Customers/DetailsNoCustomer.cshtml
<h1>There is No Customer Like that</h1>

Vidly/Views/Customers/Index.cshtml
@model IEnumerable<Vidly.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
        <thead>
            <tr>
                <th>Customers</th>
                <th>Discount Rate</th>
            </tr>
        </thead>
    <tbody>
        @foreach (var item in Model)
        {
                <tr>
                    <td>
                    @Html.DisplayFor(modelItem => item.Name) 
                    </td>

                    <td>
                    <td>@item.MembershipType.DiscountRate</td> 
                    @Html.ActionLink("Edit", "Edit", new {/*name=item.Name */}) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
        }
    </tbody>
</table>

Vidly/Views/Movies/Random.cshtml
@model Vidly.ViewModels.RandomMoveViewModel
@{
    ViewData["Title"] = "Random";
}

<h1>Random</h1>


<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    
    <tbody>
@foreach (var item in Model.Customers) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new {name=item.Name }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vidly</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vidly.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Index">Vidly</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Random">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Vidly - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>